version: '3.8'

services:
  playermaker:
    container_name: playermaker
    image: playermaker:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8081:8080
    environment:
      JVM_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      JMX_PORT: '5555'


